# Generated by Django 5.1.3 on 2025-03-25 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('large_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('License_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('License_Name', models.CharField(max_length=255)),
                ('License_Valid', models.BooleanField()),
                ('LicenseValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('dataset', models.CharField(max_length=255)),
                ('ROUGE1', models.FloatField()),
                ('ROUGE2', models.FloatField()),
                ('ROUGE_L', models.FloatField()),
                ('ROUGE_LSum', models.FloatField()),
                ('BERTScoreF1', models.FloatField()),
                ('BERTScorePrecision', models.FloatField()),
                ('BERTScoreRecall', models.FloatField()),
                ('STSScore', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('binary_content', models.BinaryField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DocDescription', models.CharField(max_length=255)),
                ('DocLink', models.CharField(max_length=255)),
                ('LastDateScraped', models.DateField()),
                ('DocName', models.CharField(max_length=255)),
                ('RequiresAttribution', models.BooleanField()),
                ('DocValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.license')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('Answer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Link', models.CharField(max_length=255, null=True)),
                ('PageNum', models.IntegerField(blank=True, null=True)),
                ('Answer', models.CharField(max_length=255)),
                ('LastDayScraped', models.DateField()),
                ('CopyrightDate', models.DateField(blank=True, null=True)),
                ('OutdatedFlag', models.IntegerField(blank=True, null=True)),
                ('FlagNewAnswerID', models.IntegerField(blank=True, null=True)),
                ('AnswerRating', models.IntegerField(blank=True, null=True)),
                ('AnswerValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('Doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.document')),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.license')),
                ('Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('RevAnswer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ScoreScale', models.IntegerField(help_text='Rating between 1 (worst) and 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Description', models.CharField(help_text='Brief description of the answer', max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.question')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedDataMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField()),
                ('content_preview', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('scraped_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='lmforge_core.scrapeddata')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('SourceID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('SourceName', models.CharField(max_length=255)),
                ('SourceDescription', models.CharField(max_length=255)),
                ('SourceLink', models.CharField(max_length=255)),
                ('SourceValid', models.IntegerField(choices=[(1, 'Random/Unverified'), (2, 'Sourced'), (3, 'Published/audited/GovData')], default=1)),
                ('License_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.license')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='Source_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmforge_core.source'),
        ),
    ]
