# Generated by Django X.X on 2025-10-10 00:35

from django.db import migrations

# These are the SQL commands to fix the character set.
# NOTE: Replace 'your_database_name' with your actual database name.
SQL_COMMANDS = """
ALTER DATABASE mis4000cob_Autoprophet CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE lmforge_core_scrapeddata CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE lmforge_core_scrapeddata MODIFY COLUMN content LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('lmforge_core', '0001_initial'), 
    ]

    operations = [
        migrations.RunSQL(SQL_COMMANDS, reverse_sql=migrations.RunSQL.noop),
    ]
