# Generated by Django 4.2.23 on 2026-02-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmforge_core', '0002_fix_mysql_charset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document_y',
        ),
    ]
